image: Ubuntu

stack: jdk 11
branches:
  only:
    - master

build: off

install:
  - ps: $App = Start-Process -FilePath java -ArgumentList "-jar ./artifacts/app-order.jar" -PassThru

build_script:
  -  chmod +x gradlew
  - ps: ./gradlew test --info "-Dselenide.headless=true"

on_finish:
  - ps: Stop-Process -Id $App.Id

